### ISSUE TITLE
first bug: regarding UI5 button event handler registration

### ISSUE THREAD

**Issue by ghost** [Emmachen/SapUi5Test#1]
Hi 文心，

我把你的project clone下来一一做检查。

先说第一个问题：press button点了不work。

![clipboard1](https://cloud.githubusercontent.com/assets/5669954/15217841/ebdcc14a-188f-11e6-8dee-367a740fbd11.png)
我是怎么分析的呢？

首先在Chrome development tool里看到如下的error：

![clipboard2](https://cloud.githubusercontent.com/assets/5669954/15217872/0b921882-1890-11e6-93e9-2c3ed73f7876.png)

点击那个小的三角符号，能够看到出error的callstack：
![clipboard3](https://cloud.githubusercontent.com/assets/5669954/15217883/18c79108-1890-11e6-90c8-4786c47eed48.png)

把鼠标放在第一个超链接上，就是那个sap-ui-core-dbg.js 27747上，点一下，能跳到源代码里去：
![clipboard4](https://cloud.githubusercontent.com/assets/5669954/15217896/246984d0-1890-11e6-89fa-16425cac945a.png)

Chrome自动告诉你是line 27747行导致的错误。

错误的具体原因是什么呢？我们知道call是JavaScript里function原型链上的一个方法，换句话说，只有function才能调用call方法。

但是现在是一个字符串“n”试图调用这个call方法，当然报错了。

为什么会出现一个字符串调用call方法？

Line 27745的aEventListeners.length = 2, 

![clipboard6](https://cloud.githubusercontent.com/assets/5669954/15217969/63224cca-1890-11e6-8d23-82784d146d05.png)

因为你的代码里给press这个event注册了两次listener：
![clipboard7](https://cloud.githubusercontent.com/assets/5669954/15217945/54de618a-1890-11e6-8a25-0acfe33b1410.png)

第一次是用line 18注册的，第二次是用line20的attachPress注册的。

但是，第一次在构造函数里注册事件时，press属性应该传入一个function 对象，你却传了一个String进去，所以出错了。你第二次通过attachPress的 注册，虽然正确。但是你看UI5框架的实现，事件发生后会在for loop里逐一执行listener，一旦js执行出错，整个js engine就会停止工作，因此你第二个listener永远得不到机会执行。

现在我把错误的地方注释掉了，确保只用attachPress注册事件：

![clipboard8](https://cloud.githubusercontent.com/assets/5669954/15217963/5e9ad460-1890-11e6-9c91-cb2dfa0fe465.png)

这时点击press button之后，line 21行的event handler就能够被调到了。但还是没看到期望的alert dialog。想想这是为什么？
![clipboard9](https://cloud.githubusercontent.com/assets/5669954/15217975/69c51972-1890-11e6-833c-76a84d14ec85.png)

**Comment by Emmachen** [comment]
这里看到了

**Comment by Emmachen** [comment]
Hi Jerry .学习到了这样的调试办法，注意到了press需要传入的是function.
将attatchPress里function传入参数evt，alert就可以调用了。
是因为在controller里的函数，原来没有传参，找不到eventProvider,所以getSource()方法无法执行。
传参后就可以了。（在google dev tool里会显示报错原因，get）

**Comment by ghost** [comment]
> Hi Jerry .学习到了这样的调试办法，注意到了press需要传入的是function.
> 将attatchPress里function传入参数evt，alert就可以调用了。
> 是因为在controller里的函数，原来没有传参，找不到eventProvider,所以getSource()方法无法执行。
> 传参后就可以了。（在google dev tool里会显示报错原因，get）

不错，完全正确。
